name: ECommerceWebsite CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Install .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      # Restore dependencies
      - name: Restore
        run: dotnet restore ECommerceWebsite.slnx

      # Build
      - name: Build
        run: dotnet build ECommerceWebsite.slnx --configuration Release --no-restore

      # Run tests
      - name: Test
        run: dotnet test ECommerceWebsite.slnx --configuration Release --no-build
